#!/usr/bin/env ansible-playbook
# vim:ft=ansible:
- name: Configure MaaS Server (redux) with roles
  hosts: maashost
  vars:
    maas_username: maas
    maas_password: 123test
    maas_email: greg@tacodata.com
    maas_hostonly_ip: 192.168.58.42
    maas_cluster_ip: 10.100.200.1
    maas_cluster_mask: 255.255.255.0
  roles:
    - role: loginpreferences
    - role: loginpreferences
      sudo: True
    - role: workdir
    - role: aptup
    - role: maasserver
    - role: maasvboxpower
    - role: maasutil

