- name: Update repository
  sudo: True
  apt_repository: repo='ppa:maas-maintainers/stable'

- name: Upgrade installation
  sudo: True
  apt: upgrade=dist

- name: Install MaaS
  sudo: True
  apt: name=maas force=yes update_cache=yes cache_valid_time=3600 state=installed install_recommends=yes

- name: Install MaaS-DHCP
  sudo: True
  apt: name=maas-dhcp force=yes update_cache=yes cache_valid_time=3600 state=installed install_recommends=yes

- name: Install MaaS-DNS
  sudo: True
  apt: name=maas-dns force=yes update_cache=yes cache_valid_time=3600 state=installed install_recommends=yes

- name: Create Initial Maas Region Admin user
  sudo: True
  command: /usr/sbin/maas-region-admin createadmin --username={{ maas_username }} --password={{ maas_password }} --email={{ maas_email }} creates={{ maas_startup_state }}

- name: Create Initial Maas Region Admin user semaphore
  sudo: True
  command: creates={{ maas_startup_state }} touch {{ maas_startup_state }}
